fix(democratic-csi): update cleanup.image to v0.15 structure
Breaking change in v0.15.0: cleanup.image also needs to be split into
repository/tag/pullPolicy structure.

Error: can't evaluate field registry in type interface {} at
.Values.node.cleanup.image.registry